export const createNodeData = (filter) => filter.map((data) => ({
    nodeId: data.nodeId,
    width: data.width,
    height: data.height,
    id: data.id,
    data: { label: data.nodeName },
    nodeType: data.nodeType,
    MachineType: data.MachineType,
    type: data.type,
    nodeCategory: data.nodeCategory,
    unit1Measurable: data.unit1Measurable,
    parentNode: data.parentNode,
    extent: data.extent,
    unit2Mandatory: data.unit2Mandatory,
    iconId: data.iconId,
    itemDescription: data.itemDescription,
    sourcePosition: data.sourcePosition,
    targetPosition: data.targetPosition,
    nodeImage: data.nodeImage,
    percentage_rejects: data.percentage_rejects,
    position: { x: data.xPosition, y: data.yPosition },
    date: data.date,
    style: {
        background: data.fillColor,
        color: data.FontColor,
        borderColor: data.borderColor,
        borderStyle: data.borderStyle,
        borderWidth: data.borderWidth,
        fontSize: data.FontSize,
        fontStyle: data.FontStyle,
        width: data.width,
        height: data.height,
        borderRadius: data.borderRadius,
        display: data.borderRadius ? "flex" : "",
        alignItems: data.nodeImage == null ? "center" : "",
        justifyContent: "center",
    },
}));
